/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Sun Sep 24 18:31:26 2017. */

#include "msg.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t msg_Update_fields[3] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, msg_Update, service_name, service_name, 0),
    PB_FIELD(  2, UENUM   , SINGULAR, STATIC  , OTHER, msg_Update, status, service_name, 0),
    PB_LAST_FIELD
};

const pb_field_t msg_Command_fields[2] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, msg_Command, command, command, 0),
    PB_LAST_FIELD
};





/* @@protoc_insertion_point(eof) */
