/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev at Sun Nov 26 23:03:07 2017. */

#ifndef PB_MSG_MSG_PB_H_INCLUDED
#define PB_MSG_MSG_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _msg_Update_Service {
    msg_Update_Service_ARPING = 0,
    msg_Update_Service_DOOR = 1,
    msg_Update_Service_PIR = 2,
    msg_Update_Service_CAMERA = 3
} msg_Update_Service;
#define _msg_Update_Service_MIN msg_Update_Service_ARPING
#define _msg_Update_Service_MAX msg_Update_Service_CAMERA
#define _msg_Update_Service_ARRAYSIZE ((msg_Update_Service)(msg_Update_Service_CAMERA+1))

typedef enum _msg_Update_Status {
    msg_Update_Status_OK = 0,
    msg_Update_Status_TROUBLE = 1,
    msg_Update_Status_ARMED = 2,
    msg_Update_Status_DISARMED = 3,
    msg_Update_Status_MALFUNCTIONING = 4
} msg_Update_Status;
#define _msg_Update_Status_MIN msg_Update_Status_OK
#define _msg_Update_Status_MAX msg_Update_Status_MALFUNCTIONING
#define _msg_Update_Status_ARRAYSIZE ((msg_Update_Status)(msg_Update_Status_MALFUNCTIONING+1))

typedef enum _msg_Command_Do {
    msg_Command_Do_ARM = 0,
    msg_Command_Do_DISARM = 1,
    msg_Command_Do_START_RECORD = 2,
    msg_Command_Do_STOP_RECORD = 3,
    msg_Command_Do_PANIC = 4
} msg_Command_Do;
#define _msg_Command_Do_MIN msg_Command_Do_ARM
#define _msg_Command_Do_MAX msg_Command_Do_PANIC
#define _msg_Command_Do_ARRAYSIZE ((msg_Command_Do)(msg_Command_Do_PANIC+1))

/* Struct definitions */
typedef struct _msg_Command {
    msg_Command_Do command;
/* @@protoc_insertion_point(struct:msg_Command) */
} msg_Command;

typedef struct _msg_Update {
    msg_Update_Service service_name;
    msg_Update_Status status;
/* @@protoc_insertion_point(struct:msg_Update) */
} msg_Update;

/* Default values for struct fields */

/* Initializer values for message structs */
#define msg_Update_init_default                  {(msg_Update_Service)0, (msg_Update_Status)0}
#define msg_Command_init_default                 {(msg_Command_Do)0}
#define msg_Update_init_zero                     {(msg_Update_Service)0, (msg_Update_Status)0}
#define msg_Command_init_zero                    {(msg_Command_Do)0}

/* Field tags (for use in manual encoding/decoding) */
#define msg_Command_command_tag                  1
#define msg_Update_service_name_tag              1
#define msg_Update_status_tag                    2

/* Struct field encoding specification for nanopb */
extern const pb_field_t msg_Update_fields[3];
extern const pb_field_t msg_Command_fields[2];

/* Maximum encoded size of messages (where known) */
#define msg_Update_size                          4
#define msg_Command_size                         2

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MSG_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
