MQTT_TOPIC_PREFIX = 'alarm/'

ARPING_DEVICE_MAC = ''
ARPING_DEVICE_IP = '192.168.44.140'
ARPING_FREQUENCY_SECONDS = 5
ARPING_TIMEOUT_SECONDS = 2
ARPING_MQTT_TOPIC = 'arping'

ALARM_SERVICE_MQTT_TOPIC = 'alarm'

MQTT_HOST = 'localhost'
MQTT_PORT = 1883
